<h2 style="text-align: center;"><b>Python. Numpy.</b></h2>

### modules

**Модули** - это "библиотеки" Python. То есть это самостоятельные, объединённые технически и логически, именованные части Python кода

* О модулях необходимо знать только одно - как их импортировать:

In [ ]:
import collections

* Импортировать только какой-то компонент из модуля:

In [ ]:
from collections import Counter

* Импортировать с другим именем (чаще всего используется для лаконичности кода):

In [ ]:
import collections as cl

In [ ]:
count = cl.Counter()

Жизненный пример:

In [25]:
import numpy as np

### files

Немного вспомним, как работать с файлами в Python.

В целом, в таких библиотеках, как Pandas и пр., уже есть готовые функции по считыванию данных из файлов с определёнными типами данных, однако в случае нетипичного формата данных такую функцию придётся писать самому.

In [ ]:
!echo 'test file for python-intro notebook' > test.txt

In [ ]:
path = './test.txt'

In [ ]:
file = open(path, mode='r')
print([line for line in file][0])
file.close()

test file for python-intro notebook





| Режим | Обозначение |
|-------|-------------|
| **'r'**  | Открытие на **чтение** (является значением по умолчанию) |
| **'rb'** | Открытие на **чтение**, в предположении, что будут считываться **байты** |
| **'w'** | Открытие на **запись**, содержимое файла удаляется. Если файла не существует, создается новый |
| **'wb**' | Открытие на **запись байтов**, содержимое файла удаляется. Если файла не существует, создается новый |
| **'a'** | Открытие на **дозапись**, информация добавляется **в конец файла** |
| **'r+'** | Открыть файл на **чтение И запись**. Если файла нет, **новый НЕ создаётся** |
| **'a+'** | Открыть файл на **чтение И запись в конец файла**. Если файла нет, **новый создаётся** |
| **'t'** | Открытие файла **как текстового** (по умолчанию) |

In [ ]:
with open(path, mode='r') as test_file:
    for line in test_file:
        print(line)

test file for python-intro notebook



---

# Библиотека Numpy.
- ***``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.***


- ***Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.***

In [ ]:
# !conda install numpy
# !pip3 install numpy

In [2]:
!pip install optuna

Defaulting to user installation because normal site-packages is not writeable


In [1]:
import numpy as np

## 1. Одномерные массивы

***Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.***

In [ ]:
np.lookfor('mean value of array')

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.isrealobj
    Return True if x is a not complex type or an array of complex numbers.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Retur

***Далее можно почитать документацию про контретную функцию.***

In [27]:
?np.ma.mean

In [26]:
np.con*?

***Посмотрим на количественные характеристики ``ndarray``.***

In [3]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [4]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 4 -- количество элементов по первой оси. 
size: 4 -- всего элементов в матрице. 
ndim: 1 -- размерность матрицы. 
shape: (4,) -- количество элементов по каждой оси.


In [8]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]],
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [12]:
arr[0, 0, 0]

1

In [6]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


***Индексы.***

In [7]:
a = np.array([1, 2, 3, 4])
a[0], a[-1]

(1, 4)

***Последний элемент.***

In [ ]:
a[-1]

4

***Можем изменять объекты массива.***

In [14]:
a[2] = -1
a

array([ 1,  2, -1,  4])

## Создание массивов.

In [17]:
a = np.zeros(7) # массив из нулей
b = np.ones(7, dtype=np.int16) # массив из единиц
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


***Часто нужно создать нулевой массив такой же как другой.***

In [18]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [19]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

***Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг -- целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.***

In [20]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


***Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.***

In [21]:
a = np.linspace(1, 15, 2)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


***Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.***

In [22]:
d = np.logspace(np.log10(10), np.log10(10**3), 15)
d

array([  10.        ,   13.89495494,   19.30697729,   26.82695795,
         37.2759372 ,   51.79474679,   71.9685673 ,  100.        ,
        138.94954944,  193.06977289,  268.26957953,  372.75937203,
        517.94746792,  719.685673  , 1000.        ])

## 2. Операции над одномерными массивами.

***Все арифметические операции производятся поэлементно.***

In [23]:
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


In [37]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 10)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.          -4.22222222  -6.44444444  -8.66666667 -10.88888889
 -13.11111111 -15.33333333 -17.55555556 -19.77777778 -22.        ]


ValueError: operands could not be broadcast together with shapes (11,) (10,) 

***Один из операндов может быть скаляром, а не массивом.***

In [35]:
print(5/a)
print(10 + b)

[1.66666667 0.83333333 0.55555556 0.41666667 0.33333333 0.27777778
 0.23809524 0.20833333 0.18518519 0.16666667 0.15151515]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [36]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [27]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [28]:
np.log(a)

array([1.09861229, 1.79175947, 2.19722458, 2.48490665, 2.7080502 ,
       2.89037176, 3.04452244, 3.17805383, 3.29583687, 3.40119738,
       3.49650756])

In [32]:
a = np.zeros_like(10)
b = np.zeros_like(11)
print(a == b)

True


In [41]:
a[4:]

array([15., 18., 21., 24., 27., 30., 33.])

***Логические операции также производятся поэлементно.***

In [38]:
print(a > b)
print(a == b)
print(a >= 10)

ValueError: operands could not be broadcast together with shapes (11,) (10,) 

In [30]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


***Посмотрим на сортировку numpy-массивов.***

In [42]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [43]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


***Теперь попробуем как метод.***

In [44]:
a.sort()
print(a)

[-2  0  1  5  6 10 18]


## Индексирование массивов и срезы

***Массив в обратном порядоке.***

In [47]:
print(a)
a[::-1]

[-2  0  1  5  6 10 18]


array([18, 10,  6,  5,  1,  0, -2])

***Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.***

In [ ]:
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
a[2:5]

array([1, 5, 6])

In [ ]:
b = a[0:6] # копия не создается!!!
b[1] = -1000
print(a)

[   -2 -1000     1     5     6    10    18]


***Диапозоны с шагами.***

In [ ]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

[-2  1]
[-2  0  1  5  0 10 18]


## 3. Двумерные массивы

In [48]:
a = np.array([[1, 2], [3, 4], [3,6]])
print(a)

[[1 2]
 [3 4]
 [3 6]]


In [49]:
a.ndim, a.shape, len(a), a.size

(2, (3, 2), 3, 6)

***Обращение по индексу.***

In [51]:
a[1][1], a[1,1]

(4, 4)

In [54]:
(3,)

(3,)

In [ ]:
a = np.ones((3, 3)) # подаём tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [55]:
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [56]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


***Умножение матриц.***

In [61]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [62]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b))
a =np.array([2,5,8])
b= np.array([5,3,7])
print(a.dot(b))

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]
81


***Маски.***

In [64]:
a = np.arange(20)
print(a)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


In [65]:
a = 5 * np.eye(5)
print(a)
print(a % 3 == 0)
print(a[(a % 3 == 0)][:])

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
[[False  True  True  True  True]
 [ True False  True  True  True]
 [ True  True False  True  True]
 [ True  True  True False  True]
 [ True  True  True  True False]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4. Тензоры (многомерные массивы)

In [69]:
X = np.arange(64).reshape(8, 2, 4)
print(np.arange(64))
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [67]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

In [68]:
X.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

***Посмотрим на суммы по разным осям.***

In [71]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# суммируем сразу по двум осям, то есть для фиксированной i
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


## 5. Линейная алгебра

In [72]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


***Определитель.***

In [73]:
np.linalg.det(a)

4.0



***Нахождение обратной матрицы.***

In [74]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


***Нахождение собственных значений и собственных векторов маттрицы.***

In [76]:
np.linalg.eig(a)

EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.70710678, -0.4472136 ],
       [ 0.70710678, -0.89442719]]))

***Решение СЛАУ.***

In [77]:
b = np.array([1, 4])
x = np.linalg.solve(a, b)
x

array([-0.25,  1.5 ])